revert back to secrets

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -87,73 +87,80 @@ jobs:
             exit 1
           fi
 
-  run-api:
-    name: Docker run api
-    runs-on: ubuntu-latest
-    needs: pull-api
-    steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{secrets.AWS_REGION}}
-      - name: Login to AWS ECR
-        id: login-aws-ecr
-        uses: aws-actions/amazon-ecr-login@v2
-      - name: Run API
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
-          BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
-          CLOUDFRONT_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
-          DATABASE_URL: ${{ secrets.DATABASE_URL }}
-          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
-          EMAIL_JWT_SECRET: ${{ secrets.EMAIL_JWT_SECRET }}
-          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
-          KEY_PAIR_ID_TWO: ${{ secrets.KEY_PAIR_ID_TWO }}
-          REDIS_HOST: ${{ secrets.REDIS_HOST }}
-          REDIS_PORT: ${{ secrets.REDIS_PORT }}
-          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
-          USER_LOGIN_JWT_SECRET: ${{ secrets.USER_LOGIN_JWT_SECRET }}
-          API_CONTAINER_NAME: ${{ vars.API_CONTAINER_NAME }}
-        run: |
-          echo ${{ steps.login-aws-ecr.outputs.registry }}/${{secrets.API_IMAGE_REPO}}:latest
-          docker_run_command_id=$(aws ssm send-command \
-          --document-name "AWS-RunShellScript" \
-          --targets "Key=instanceIds,Values=${{ secrets.INSTANCE_ID_1 }},${{ secrets.INSTANCE_ID_2 }}" \
-          --comment "Run Docker Image" \
-          --parameters commands='[
-            echo "parameter commands have run",
-            "aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
-            "docker run -p 3000:3000 -e REDIS_HOST=${{ secrets.REDIS_HOST }} -e REDIS_PORT=${{ secrets.REDIS_PORT }} -e STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} -e EMAIL_JWT_SECRET=${{ secrets.EMAIL_JWT_SECRET }} -e EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} -e USER_LOGIN_JWT_SECRET=${{ secrets.USER_LOGIN_JWT_SECRET }} ${{secrets. ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest"
-          ]' --query "Command.CommandId" --output text)
+  # run-api:
+  #   name: Docker run api
+  #   runs-on: ubuntu-latest
+  #   needs: pull-api
+  #   steps:
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{secrets.AWS_REGION}}
+  #     - name: Login to AWS ECR
+  #       id: login-aws-ecr
+  #       uses: aws-actions/amazon-ecr-login@v2
+  #     - name: Run API
+  #       env:
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
+  #         BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
+  #         CLOUDFRONT_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
+  #         DATABASE_URL: ${{ secrets.DATABASE_URL }}
+  #         EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
+  #         EMAIL_JWT_SECRET: ${{ secrets.EMAIL_JWT_SECRET }}
+  #         EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
+  #         KEY_PAIR_ID_TWO: ${{ secrets.KEY_PAIR_ID_TWO }}
+  #         REDIS_HOST: ${{ secrets.REDIS_HOST }}
+  #         REDIS_PORT: ${{ secrets.REDIS_PORT }}
+  #         STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
+  #         USER_LOGIN_JWT_SECRET: ${{ secrets.USER_LOGIN_JWT_SECRET }}
+  #         API_CONTAINER_NAME: ${{ vars.API_CONTAINER_NAME }}
+  #       run: |
+  #         echo ${{ steps.login-aws-ecr.outputs.registry }}/${{secrets.API_IMAGE_REPO}}:latest
+  #         docker_run_command_id=$(aws ssm send-command \
+  #         --document-name "AWS-RunShellScript" \
+  #         --targets "Key=instanceIds,Values=${{ secrets.INSTANCE_ID_1 }},${{ secrets.INSTANCE_ID_2 }}" \
+  #         --comment "Run Docker Image" \
+  #         --parameters commands='[
+  #           "aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
+  #           "docker run -p 3000:3000 \
+  #           -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
+  #           -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
+  #           -e STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
+  #           -e EMAIL_JWT_SECRET=${{ secrets.EMAIL_JWT_SECRET }} \
+  #           -e EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} \
+  #           -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
+  #           -e USER_LOGIN_JWT_SECRET=${{ secrets.USER_LOGIN_JWT_SECRET  }} \
+  #           ${{secrets. ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest"
+  #         ]' --query "Command.CommandId" --output text)
 
-          echo "docker_run_command_id=$docker_run_command_id" >> $GITHUB_ENV
-      - name: Wait for Docker RUN Command to Complete on Instance 1
-        run: |
-          aws ssm wait command-executed \
-          --command-id ${{ env.docker_run_command_id }} \
-          --instance-id ${{ secrets.INSTANCE_ID_1 }} || true \
-          --debug
-      - name: Wait for Docker RUN Command to Complete on Instance 2
-        run: |
-          aws ssm wait command-executed \
-          --command-id ${{ env.docker_run_command_id }} \
-          --instance-id ${{ secrets.INSTANCE_ID_2 }} || true \
-          --debug
-      - name: Check Command Status
-        run: |
-          docker_run_commandOutput=$(aws ssm list-commands --command-id ${{ env.docker_run_command_id }} --output json) 
-          echo $docker_run_commandOutput | jq
+  #         echo "docker_run_command_id=$docker_run_command_id" >> $GITHUB_ENV
+  #     - name: Wait for Docker RUN Command to Complete on Instance 1
+  #       run: |
+  #         aws ssm wait command-executed \
+  #         --command-id ${{ env.docker_run_command_id }} \
+  #         --instance-id ${{ secrets.INSTANCE_ID_1 }} || true \
+  #         --debug
+  #     - name: Wait for Docker RUN Command to Complete on Instance 2
+  #       run: |
+  #         aws ssm wait command-executed \
+  #         --command-id ${{ env.docker_run_command_id }} \
+  #         --instance-id ${{ secrets.INSTANCE_ID_2 }} || true \
+  #         --debug
+  #     - name: Check Command Status
+  #       run: |
+  #         docker_run_commandOutput=$(aws ssm list-commands --command-id ${{ env.docker_run_command_id }} --output json)
+  #         echo $docker_run_commandOutput | jq
 
-          docker_run_command_status=$(aws ssm list-commands --command-id ${{ env.docker_run_command_id }} --query "Commands[0].StatusDetails" --output text)
-          echo $docker_run_command_status
+  #         docker_run_command_status=$(aws ssm list-commands --command-id ${{ env.docker_run_command_id }} --query "Commands[0].StatusDetails" --output text)
+  #         echo $docker_run_command_status
 
-          if [ $docker_run_command_status == "Success" ]; then
-            echo "Command executed SUCCESSFULLY. API is up and running"
-          else 
-            echo "Docker Container FAILED to start"
-            exit 1
-          fi
+  #         if [ $docker_run_command_status == "Success" ]; then
+  #           echo "Command executed SUCCESSFULLY. API is up and running"
+  #         else
+  #           echo "Docker Container FAILED to start"
+  #           exit 1
+  #         fi
