finished CI/DI pipeline by adding ECR Pull and Docker Run command

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -33,3 +33,56 @@ jobs:
           echo ${{secrets.API_IMAGE_REPO}}
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
+  deploy-api:
+    name: Deploy API to EC2
+    runs-on: ubuntu-latest
+    needs: build-api
+    steps:
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{secrets.AWS_REGION}}
+      - name: Login to AWS ECR
+        id: login-aws-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+      - name: Pull and Run Docker Image From ECR
+        run: |
+          command_id=$(aws ssm send-command \
+          --document-name "AWS-RunShellScript" \
+          --targets "Key=instanceids,Values=${{ secrets.INSTANCE_ID_1 }},${{ secrets.INSTANCE_ID_2 }}" \
+          --comment "Pull Docker image and run it" \
+          --parameters commands='[
+            "aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
+            "docker stop ${{ vars.API_CONTAINER_NAME }} || true",
+            "docker pull ${{ steps.login-aws-ecr.outputs.registry }}/${{secrets.API_IMAGE_REPO}}:latest",
+            "docker run --rm -d -p 3000:3000 -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -e BUCKET_NAME=${{ secrets.BUCKET_NAME }} -e BUCKET_REGION=${{ secrets.BUCKET_REGION }} -e CLOUDFRONT_DISTRIBUTION=${{ secrets.CLOUDFRONT_DISTRIBUTION }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} -e EMAIL_JWT_SECRET=${{ secrets.EMAIL_JWT_SECRET }} -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} -e KEY_PAIR_ID_TWO=${{ secrets.KEY_PAIR_ID_TWO }} -e PRIVATE_KEY_TWO=${{ secrets.PRIVATE_KEY_TWO }} -e REDIS_HOST=${{ secrets.REDIS_HOST }} -e REDIS_PORT=${{ secrets.REDIS_PORT }} -e STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} -e USER_LOGIN_JWT_SECRET=${{ secrets.USER_LOGIN_JWT_SECRET }} --name ${{ vars.API_CONTAINER_NAME }} ${{ steps.login-aws-ecr.outputs.registry }}/${{secrets.API_IMAGE_REPO }}:latest"
+          ]' --query "Command.CommandId" --output text)
+
+          echo "command_id=$command_id" >> $GITHUB_ENV
+      - name: Wait for Docker Commands to Complete on Instance 1
+        run: |
+          echo ${{ env.command_id }}
+          aws ssm wait command-executed \
+          --command-id ${{ env.command_id }} \
+          --instance-id ${{ secrets.INSTANCE_ID_1 }} || true
+      - name: Wait for Docker Commands to Complete on Instance 2
+        run: |
+          echo ${{ env.command_id }}
+          aws ssm wait command-executed \
+          --command-id ${{ env.command_id }} \
+          --instance-id ${{ secrets.INSTANCE_ID_2 }} || true
+      - name: Check Command Status
+        run: |
+          status=$(aws ssm list-commands --command-id ${{ env.command_id }} --query "Commands[0].StatusDetails" --output text)
+
+          echo $status
+
+          if [ $status == "Success" ]; then
+            echo "Command executed Successfully. API is up and running"
+          else 
+            echo "Command failed"
+            exit 1
+          fi
